ProductionID: Fake_Obs
SN parameters:
   Id : 100                   # Id of the first SN
   X1_Color:                    # stretch and color
       type : fixed
       min : [0.0,0.0]
       max : [2.0,0.2]
       rate :  JLA
   z :              # redshift
       type : uniform
       min : 0.01
       max : 0.5
       step: 0.05
       rate : Perrett # Type Ia volumetric rate : Perrett, Ripoche, Dilday.
   DayMax:                 # Tmax (obs. frame)
       type : unique #uniform or random or unique
       step : 1 # if uniform: step (in day) between Tmin(obs) and Tmax(obs)      
   min_rf_phase : -20.        # obs min phase (rest frame)
   max_rf_phase : 60.         # obs max phase (rest frame)
   absmag : -19.0906          # peak abs mag
   band : bessellB             # band for absmag
   magsys : vega              # magsys for absmag
Cosmology:
   Model : w0waCDM      # Cosmological model
   Omega_m : 0.30             # Omega_m
   Omega_l : 0.70             # Omega_l
   H0 : 72.0                  # H0
   w0 : -1.0                  # w0
   wa : 0.0                   # wa
Instrument:
   name : LSST       #name of the telescope (internal)
   throughput_dir : LSST_THROUGHPUTS_BASELINE #dir of throughput
   atmos_dir : THROUGHPUTS_DIR   #dir of atmos
   airmass : 1.1   #airmass value
   atmos : True  #atmos
   aerosol : False  #aerosol
Observations: 
   filename: ../flatiron/maf_local/sims_maf_contrib/tutorials/baseline2018a.db  # Name of db obs file (full path)
   fieldtype: DD #DD or WFD
Simulator :
    name : SN_Cosmo           # Simulator name: SN_Cosmo,SN_Sim,SN_Ana
    model : salt2-extended   # spectra model
    version : 1.0                     #version
Host Parameters: None         # Host parameters
Display : False #display during LC simulations
Output:
    directory: Output_Simu
    save: True
Multiprocessing:
    nproc: 4
Metric: SN_Simulation